    #!/bin/bash       
    #@ job_name=amr3d
    #@ job_type=parallel  
    #@ class=large
    #@ notification=always 
    #@ error = ./visc.err 
    #@ output =./visc.log 
    #@ blocking = unlimited
    #@ total_tasks = 8
    #@ node_usage = shared 
    #@ network.mpi = csss,shared,us
    # use css0 on the SP3
    #@ queue 

    poe ./amr3d.AIX.mpCC_r.f77.DEBUG.MPI.ex inputs.viscoelastic.bubble3d >> run.out
