#ifndef N_EXTRA_REAL_H_
#define N_EXTRA_REAL_H_

#if (0)
x,y,z is core (base); x0,y0,z0,u,v,w,T, (REAL) 
and material_id (int) are extra
#endif

#define N_EXTRA_REAL (7)
#define N_EXTRA_REAL_X0 (0)
#define N_EXTRA_REAL_Y0 (1)
#define N_EXTRA_REAL_Z0 (2)
#define N_EXTRA_REAL_u (3)
#define N_EXTRA_REAL_v (4)
#define N_EXTRA_REAL_w (5)
#define N_EXTRA_REAL_T (6)

#define N_EXTRA_INT (1)
#define N_EXTRA_INT_MATERIAL_ID (0)

#endif
