    #!/bin/bash       
    #@ job_name=amr
    #@ job_type=parallel  
    #@ class=interactive
    #@ notification=always 
    #@ error = ./dambreak.err 
    #@ output =./dambreak.log 
    #@ wall_clock_limit = 00:10:00
    #@ node = 1 
    #@ tasks_per_node = 2 
    #@ node_usage = shared 
    #@ network.mpi = css0,shared,us
    #@ queue 

    poe ./amr2d.AIX.mpCC.f77.DEBUG.MPI.ex inputs.parallel >> run.out
