/*
 * DO NOT EDIT THIS FILE! It was created automatically by ./makeopts.
 */

char *vpCompilerOptions = "-g -O -O3 -DNDEBUG -DUSE_TIMER -DCOMP_AC11B -DCOMP_AC31B -DCOMP_AC32B -DCOMP_AR11B -DCOMP_AR31B -DCOMP_AR32B -I. -DBL_BYTEORDER_LITTLE_ENDIAN";
