#ifdef BL_USE_FLOAT

#define CPP_EPS99 (1.0e-30)
#define CPP_EPS30 (1.0e-30)
#define CPP_EPS15 (1.0e-6)
#define CPP_EPS14 (1.0e-6)
#define CPP_EPS13 (1.0e-6)
#define CPP_EPS12 (1.0e-6)
#define CPP_EPS11 (1.0e-6)
#define CPP_EPS10 (1.0e-6)
#define CPP_EPS9 (1.0e-6)
#define CPP_EPS8 (1.0e-6)
#define CPP_EPS7 (1.0e-6)
#define CPP_EPS6 (1.0e-6)
#define CPP_EPS5 (1.0e-5)
#define CPP_EPS4 (1.0e-4)

#else

#define CPP_EPS99 (1.0e-30)
#define CPP_EPS30 (1.0e-30)
#define CPP_EPS15 (1.0e-15)
#define CPP_EPS14 (1.0e-14)
#define CPP_EPS13 (1.0e-13)
#define CPP_EPS12 (1.0e-12)
#define CPP_EPS11 (1.0e-11)
#define CPP_EPS10 (1.0e-10)
#define CPP_EPS9 (1.0e-9)
#define CPP_EPS8 (1.0e-8)
#define CPP_EPS7 (1.0e-7)
#define CPP_EPS6 (1.0e-6)
#define CPP_EPS5 (1.0e-5)
#define CPP_EPS4 (1.0e-4)

#endif
